---
name: Tag-Workflow-1
on:

  workflow_dispatch:

    inputs:
      commit-ID:
        description: Enter commit ID or Branch name
        required: true
        default: ''
        type: text
      rename:
        description: Do you want to rename the tag? say yes or no
        required: true
        type: string
        options:
          - yes
          - no
      suffix:
        description: Enter suffix name to tag
        required: true
        default: ''
        type: text

 
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2



      - name: run
        run: |
         #!/bin/bash

         git ls-remote --heads >/dev/null 2>&1
         branch_commit_ID="${{ github.event.inputs.commit-ID }}"
         if ! git rev-parse --verify $branch_commit_ID >/dev/null 2>&1
         then
         echo "Error: $branch_commit_ID is not a valid commit ID or Branch name"
         exit 0
         else
         echo " $branch_commit_ID is valid commit ID or Branch name"
         fi
         answer="${{ github.event.inputs.rename }}"
         while [ "$answer" != "yes" ] && [ "$answer" != "no" ]
         do
         echo " do you want to rename the tag? Please answer with 'yes' or 'no': "
         exit 0
         done
         if [ "$answer" == "yes" ]
         then

         suffix_name="${{ github.event.inputs.suffix }}"
         TEMP="dummy-$suffix_name"
         while git ls-remote --tags | grep -q $TEMP
         do
         echo " Error: $TEMP is already exists.. Please change the suffix name "
         exit 0
         done
         echo " Tag name changing to $TEMP "
         else
         echo " Tag will not be renamed "
         fi

         #git checkout tag/test
         if [ "$answer" == "yes" ]
         then
         git config --local remote.origin.fetch "+refs/tags/*:refs/tags/*" >/dev/null 2>&1
         git fetch origin >/dev/null

         git checkout dummy
         echo " renaming the tag name.. "
         git tag -f $TEMP dummy
         echo " renamed to $TEMP "
         echo " deleting the tag.. "
         git tag -d dummy || true
         echo " tag deleted "

         git push origin $TEMP


         fi
         
         git fetch origin $branch_commit_ID
         git branch dumm FETCH_HEAD
         git checkout dumm
         


         
         git tag dummy 
         git push origin --delete dummy 
         git push origin dummy
         echo " dummy tag is created succussfully "
