name: My Workflow

on:
  workflow_dispatch:
    inputs:
      commit-ID:
        description: 'Enter the commit ID'
        required: true
        default: '' 
        type: text
      rename:
        description: 'Do you want to rename the tag for backup'
        required: true
        default: 'true' 
        type: boolean

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set executable permission
      run: chmod +x ./script.sh
    - name: Run script
      run: |
        ./script.sh "${{ github.event.inputs.commit-ID }}" "${{ github.event.inputs.rename }}"

