name: My Workflow

on:
  push:
    branches: [ main ]

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set executable permission
      run: chmod +x ./script.sh
      
    - name: Run script
      run: ./script.sh $1 $2
