name: My Workflow


on:
  workflow_dispatch:
    inputs:
      commit-ID:
        description: 'enter the commit ID'
        required: true
        default: '' 
        type: text
      rename:
        description: 'Do you want to rename the tag for backup'
        required: true
        default: '' 
        type: bolean
env:
  $1: ${{github.event.inputs.Branch/Commit-ID}}  
  $2: ${{github.event.inputs.rename}}

jobs:
  my-job:
    runs-on: ubuntu-latest
    

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set executable permission
      run: chmod +x ./script.sh
      
    - name: Run script
      run: ./script.sh $1 $2
