name: My Workflow

on:
  push:
    branches: [ main ]
env:
  branch_commit_ID : ${{github.event.inputs.Branch/Commit-ID}}  
  ans: ${{github.event.inputs.rename-yes/no}}

jobs:
  my-job:
    runs-on: ubuntu-latest
    

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set executable permission
      run: chmod +x ./script.sh
      
    - name: Run script
      run: ./script.sh $1 $2
