name: Workflow Dispatch

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch name'
        required: true
      commit_id:
        description: 'The commit ID'
        required: true

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check commit ID or branch
        uses: actions/github-script@v4
        with:
         
          ref: ${{ github.event.inputs.branch }}
          script: |
            const ref = process.env.INPUT_BRANCH || process.env.INPUT_COMMIT_ID;
            const octokit = require('@octokit/rest')();
            octokit.authenticate({
              type: 'token',
              token: process.env.GITHUB_TOKEN
            });
            const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
            let sha;
            try {
              sha = await octokit.git.getRef({
                owner: owner,
                repo: repo,
                ref: ref
              });
              console.log(`Commit ID or branch '${ref}' found: ${sha.data.object.sha}`);
            } catch (error) {
              console.log(`Commit ID or branch '${ref}' not found: ${error.message}`);
              process.exit(1);
            }
