name: Check Commit ID or Branch

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'

jobs:
  check-commit-id-or-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check commit ID or branch
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const ref = process.env.GITHUB_REF;
            const octokit = require('@octokit/rest')();
            octokit.authenticate({
              type: 'token',
              token: process.env.GITHUB_TOKEN
            });
            const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
            let sha;
            try {
              sha = await octokit.git.getRef({
                owner: owner,
                repo: repo,
                ref: ref
              });
              console.log(`Commit ID or branch '${ref}' found: ${sha.data.object.sha}`);
            } catch (error) {
              console.log(`Commit ID or branch '${ref}' not found: ${error.message}`);
              process.exit(1);
            });
