name: Check commit/branch

on: [workflow_dispatch]

jobs:
  check-commit-branch:
    runs-on: ubuntu-latest
    steps:
    - name: Check if commit/branch exists
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const branchCommitId = "${{ github.event.inputs.commit-ID }}";
          const { context, github } = require('@actions/github');
          const octokit = new github.getOctokit("${{ secrets.GITHUB_TOKEN }}");
          try {
            const response = await octokit.repos.getCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: branchCommitId
            });
            console.log(`Commit ${branchCommitId} exists`);
          } catch (error) {
            console.log(`Error: ${branchCommitId} is not a valid commit or branch`);
            process.exit(1);
          }
