name: My Workflow

on:
  push:
   branches: []
  workflow_dispatch:
    inputs:
      commit-ID:
        description: 'Enter the commit ID'
        required: true
        default: '' 
        type: text
      rename:
        description: 'Do you want to rename the tag for backup'
        required: true 
        type: string
        options:
          - 'Yes'
          - 'No'

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: test
    - name: Set executable permission
      run: chmod +x ./script.sh
    - name: Run script
      run: |
        ./script.sh "${{ github.event.inputs.commit-ID }}" "${{ github.event.inputs.rename }}"
